name: prctr-hsa-hw12

services:
  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"
    volumes:
      - ./redis2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management Plugin port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # jumpbox:
  #   build: ./jumpbox
  #   container_name: jumpbox
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./jumpbox:/app
  #   command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
  #   depends_on:
  #     - redis1
  #     - redis2

  # myapi:
  #   build: ./myapi
  #   ports:
  #     - "9090:8000"
  #   volumes:
  #     - ./myapi:/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  #   depends_on:
  #     - redis1
  #     - redis2

  # load-test:
  #   build: ./load-test
  #   volumes:
  #     - ./load-test/scripts:/scripts

networks:
  default:
    driver: bridge

